@startuml Inheritance

title Vehicle

class Vehicle {
    #manufacturer: String
    #year: int
    #color: String
    --
    +getManufacturer()
    +getYear()
    +getColor()
    --
    +setManufacturer()
    +setYear()
    +setColor()
    --
    +Vehicle()
    +Vehicle(manufacturer, year, color)
    --
    +start()
    +stop()
    +drive() 
    +toString()
}

class Car extends Vehicle { 
    +openSunRoof()

}

class Truck extends Vehicle {
    +transport() 
}

class Bus extends Vehicle{ 
    +scheduling()
}

class SchoolBus extends Bus {
    +getFare()
}


hide empty member

@enduml